FROM bde2020/spark-master:3.3.0-hadoop3.3

# Alpine packages
RUN apk add --no-cache \
    build-base \
    python3-dev \
    musl-dev

# Install wheel first
RUN python3 -m pip install --upgrade pip setuptools wheel

# Install Python dependencies
RUN python3 -m pip install \
    requests==2.27.1 \
    python-dotenv==0.21.1 \
    schedule==1.2.2 \
    fastavro==0.23.6 \
    clickhouse-connect